services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - k-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: student
      MYSQL_PASSWORD: student123
      MYSQL_DATABASE: student_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - k-network
    volumes:
      - mysql-s-data:/var/lib/mysql

networks:
  k-network:
    driver: bridge


volumes:
    mysql-s-data: