spring.application.name=SpringJDBCEx


spring.database.url=jdbc.mysql://localhost:3306/dbname
spring.database.username=username
spring.database.password=password
spring.database.driver-class-name=com.mysql.cj.jdbc.Driver