version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      s-network:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USERNAME : root;
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "3306:3306"
    networks:
      s-network:

  networks:
    s-network:
      driver: bridge