
spring.application.name=SpringEcom

# =========================

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

# =========================
# Gemini Chat
# =========================
spring.ai.google.genai.api-key=key
spring.ai.google.genai.chat.model=gemini-3.5-flash

# =========================
# Gemini Embeddings
# =========================
spring.ai.google.genai.embedding.api-key=key
spring.ai.google.genai.embedding.text.model=gemini-embedding-2
spring.ai.google.genai.embedding.text.dimensions=1536

# =========================
# Gemini Image Generation
# =========================
spring.ai.google.genai.image.model=gemini-2.5-flash-image
spring.ai.google.genai.image.n=1
spring.ai.google.genai.image.aspect-ratio=1:1

# =========================
# File Upload
# =========================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# =========================
# SQL
# =========================
spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always

# =========================
# Spring
# =========================
spring.main.allow-bean-definition-overriding=true

# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:64349/telusko
spring.datasource.username=docker_db
spring.datasource.password=docker_db
spring.datasource.driver-class-name=org.postgresql.Driver